# build container
name: Push to release branches
on:
  push:
    branches: [master]
jobs:
  release:
    name: Release to docker registry on github.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: trailmix/dnsmasqpxe
          dockerfile: .docker/Dockerfile
          tag_with_ref: true
